receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 12s

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    tls:
      insecure: true
    endpoint: jaeger:4317
  otlp/aspire:
    tls:
      insecure: true
    endpoint: aspire:18889

  prometheus:
    endpoint: 0.0.0.0:9090
    namespace: testapp
  
extensions:
  health_check: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger, otlp/aspire]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus, otlp/aspire]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/aspire]
