name: prometheus-and-grafana

networks:
  monitoring:
    external: false
  grafana:
    external: false


services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

  prometheus_alertmanager:
    image: prom/alertmanager:latest
    container_name: prometheus_alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - monitoring

  prometheus_node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: prometheus_node_exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - monitoring

  prometheus_prom2teams:
    image: idealista/prom2teams:3.2.3
    container_name: prometheus_prom2teams
    environment:
      PROM2TEAMS_CONNECTOR: "https://prod-156.westeurope.logic.azure.com:443/workflows/b8ae13484b124b148515273c843ccaf2/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=H2EBFv_xpXNWaTShyDnIpPN4CqkSYMaId3hydP280PM"
    ports:
      - 8089:8089

  prometheus_pushgateway:
    image: prom/pushgateway
    container_name: prometheus_pushgateway
    ports:
      - "9091:9091"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_DATASOURCE: prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring
    
  grafana_loki:
    image: grafana/loki
    container_name: grafana_loki
    ports:
      - "3100:3100"
    networks:
      - monitoring

  grafana_promtail:
    image: grafana/promtail
    container_name: grafana_promtail
    volumes:
      # - ./promtail:/etc/promtail
      - ./data/promtail:/var/log/promtail
    networks:
      - monitoring
  
  grafana_alloy:
    image: grafana/alloy
    container_name: grafana_alloy
    ports:
      - 12345:12345
    volumes:
      - ./data/alloy:/var/lib/alloy
      - ./alloy/config.alloy:/usr/local/etc/alloy/config.alloy
    networks:
      - grafana

  emitter_python:
    build:
      context: ./emitter/python
    container_name: emitter_python
    ports:
      - 5000:5000
    networks:
      - monitoring

  emitter_shoehub:
    build:
      context: ./emitter/shoehub
    container_name: emitter_shoehub
    ports:
      - 5001:8080
    networks:
      - monitoring
