name: 'examples_receivers_jaeger'

services:
  receivers_jaeger:
    image: jaegertracing/all-in-one:1.58
    container_name: receivers_jaeger
    ports:
      - 16686:16686

networks:
  default:
    external: true
    name: examples-opentelemetry-default
