name: otel-receivers-grafana

services:
  grafana:
    image: grafana/grafana-oss
    container_name: otel-receivers-grafana
    ports:
      - "3000:3000"
    environment:
      GF_DATASOURCE: prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - monitoring
    
  grafana-alloy:
    image: grafana/alloy
    container_name: otel-receivers-grafana-alloy
    ports:
      - 12345:12345
    volumes:
      - ./data/alloy:/var/lib/alloy/
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    command: 
      - "run"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"
    networks:
      - grafana

  grafana-loki:
    image: grafana/loki
    container_name: otel-receivers-grafana-loki
    ports:
      - "3100:3100"
    networks:
      - monitoring

  grafana-promtail:
    image: grafana/promtail
    container_name: otel-receivers-grafana-promtail
    volumes:
      # - ./promtail:/etc/promtail
      - ./data/promtail:/var/log/promtail
    networks:
      - monitoring
  
  grafana-tempo:
    image: grafana/tempo
    container_name: otel-receivers-grafana-tempo
    volumes:
      - ./data/grafana_tempo:/var/lib/tempo
    ports:
      - 3200:3200
    networks:
      - monitoring

networks:
  default:
    external: true
    name: examples-opentelemetry-default
  monitoring:
    external: false
  grafana:
    external: false
