name: otel-emitters-nodejs

services:
  go-service:
    build:
      context: ./service/
      dockerfile: Dockerfile      
    container_name: otel-emitters-go-service
    ports:
      - "8020:8020"

networks:
  default:
    external: true
    name: examples-opentelemetry-default
