name: otel-emitters-python

services:
  python-dice:
    build:
      context: ./dice
      dockerfile: Dockerfile
    container_name: otel-emitters-python-dice
    ports:
      - 8050:8050
    networks:
      - monitoring

networks:
  default:
    external: true
    name: examples-opentelemetry-default
  monitoring:
    external: false
  grafana:
    external: false
