name: examples_emitter_python

services:
  emitter_python_random:
    build:
      context: ./random
    container_name: emitter_python_random
    ports:
      - 8050:5000
    networks:
      - monitoring

  emitter_python_shoehub:
    build:
      context: ./emitter/shoehub
    container_name: emitter_python_shoehub
    ports:
      - 5001:8080
    networks:
      - monitoring

networks:
  default:
    external: true
    name: examples-opentelemetry-default
  monitoring:
    external: false
  grafana:
    external: false
