name: otel_emitter_python

services:
  python_random:
    build:
      context: ./random
      dockerfile: Dockerfile
    container_name: emitter_python_random
    ports:
      - 8050:5000
    networks:
      - monitoring

  python_shoehub:
    build:
      context: ./shoehub
      dockerfile: Dockerfile
    container_name: emitter_python_shoehub
    ports:
      - 5001:8080
    networks:
      - monitoring

networks:
  default:
    external: true
    name: examples-opentelemetry-default
  monitoring:
    external: false
  grafana:
    external: false
