name: examples_opentelemetry_emitter_nodejs

services:
  emitter_nodejs_dice:
    build:
      context: .
      dockerfile: ./dice/Dockerfile
    container_name: emitter_nodejs_dice
    ports:
      - "8030:8030"

networks:
  default:
    external: true
    name: examples-opentelemetry-default
