name: otel_emitter_nodejs
services:
  nodejs_dice:
    build:
      context: ./dice/
      dockerfile: Dockerfile
    container_name: emitter_nodejs_dice
    ports:
      - "8030:8030"

networks:
  default:
    external: true
    name: examples-opentelemetry-default
