// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: propagator/propagator.proto

package propagator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MyRequest) Reset() {
	*x = MyRequest{}
	mi := &file_propagator_propagator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyRequest) ProtoMessage() {}

func (x *MyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_propagator_propagator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyRequest.ProtoReflect.Descriptor instead.
func (*MyRequest) Descriptor() ([]byte, []int) {
	return file_propagator_propagator_proto_rawDescGZIP(), []int{0}
}

func (x *MyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MyResponse) Reset() {
	*x = MyResponse{}
	mi := &file_propagator_propagator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyResponse) ProtoMessage() {}

func (x *MyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_propagator_propagator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyResponse.ProtoReflect.Descriptor instead.
func (*MyResponse) Descriptor() ([]byte, []int) {
	return file_propagator_propagator_proto_rawDescGZIP(), []int{1}
}

func (x *MyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_propagator_propagator_proto protoreflect.FileDescriptor

var file_propagator_propagator_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x70, 0x61, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70,
	0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x1f, 0x0a, 0x09, 0x4d, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0a, 0x4d, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x4d, 0x0a, 0x0d, 0x4d, 0x79, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x4d, 0x79, 0x52, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x4d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x70,
	0x61, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x84, 0x01, 0x0a, 0x25, 0x64, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x74, 0x68,
	0x69, 0x6e, 0x6b, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x42, 0x16, 0x50, 0x72, 0x6f,
	0x70, 0x61, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x41, 0x76, 0x65, 0x72, 0x67, 0x69, 0x73, 0x73, 0x62, 0x65,
	0x72, 0x6c, 0x69, 0x6e, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2d, 0x6f, 0x70, 0x65,
	0x6e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x65, 0x6d, 0x69, 0x74, 0x74,
	0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_propagator_propagator_proto_rawDescOnce sync.Once
	file_propagator_propagator_proto_rawDescData = file_propagator_propagator_proto_rawDesc
)

func file_propagator_propagator_proto_rawDescGZIP() []byte {
	file_propagator_propagator_proto_rawDescOnce.Do(func() {
		file_propagator_propagator_proto_rawDescData = protoimpl.X.CompressGZIP(file_propagator_propagator_proto_rawDescData)
	})
	return file_propagator_propagator_proto_rawDescData
}

var file_propagator_propagator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_propagator_propagator_proto_goTypes = []any{
	(*MyRequest)(nil),  // 0: propagator.MyRequest
	(*MyResponse)(nil), // 1: propagator.MyResponse
}
var file_propagator_propagator_proto_depIdxs = []int32{
	0, // 0: propagator.MyGrpcService.MyRpcMethod:input_type -> propagator.MyRequest
	1, // 1: propagator.MyGrpcService.MyRpcMethod:output_type -> propagator.MyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_propagator_propagator_proto_init() }
func file_propagator_propagator_proto_init() {
	if File_propagator_propagator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_propagator_propagator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_propagator_propagator_proto_goTypes,
		DependencyIndexes: file_propagator_propagator_proto_depIdxs,
		MessageInfos:      file_propagator_propagator_proto_msgTypes,
	}.Build()
	File_propagator_propagator_proto = out.File
	file_propagator_propagator_proto_rawDesc = nil
	file_propagator_propagator_proto_goTypes = nil
	file_propagator_propagator_proto_depIdxs = nil
}
