name: 'otel-collectors-opentelemetry-contrib'

services:
  collector-opentelemetry-contrib:
    image: otel/opentelemetry-collector-contrib:0.104.0
    container_name: collector-contrib
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4317:4317" # OLTP receiver over GRPC
      - "4318:4318" # OTLP receiver over HTTP
      - "13133:13133" # health_check extension
#      - 1888:1888 # pprof extension
#      - 8888:8888 # Prometheus metrics exposed by the Collector
#      - 8889:8889 # Prometheus exporter metrics
#      - 13133:13133 # health_check extension
#      - 55679:55679 # zpages extension
    volumes:
      - "./config/collector-contrib-config.yaml:/etc/otelcol/config.yaml"
      - ./logs/collector-contrib.json:/logs/collector.json
  
networks:
  default:
    external: true
    name: examples-opentelemetry-default
