global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: "30s" # Set the evaluation interval to every 1 minute. Default is every 1 minute.

rule_files:
  - "./rules/alerts.yml"
  - "./rules/recordings.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093


scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - 'node_exporter:9100'
