name: 'otel_collectors_opentelemetry'

services:
  collector_opentelemetry:
    image: otel/opentelemetry-collector:0.104.0
    container_name: collector
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "5317:4317" # OLTP receiver over GRPC
      - "5318:4318" # OTLP receiver over HTTP
    volumes:
      - "./config/collector-config.yaml:/etc/otelcol/config.yaml"
      - ./logs/collector.json:/logs/collector.json

networks:
  default:
    external: true
    name: examples-opentelemetry-default
