name: otel-emitters-cs

services:
  cs-shoehub:
    build:
      context: ./shoehub
      dockerfile: Dockerfile
    container_name: otel-emitters-cs-shoehub
    ports:
      - 5001:8080
    networks:
      - monitoring

networks:
  default:
    external: true
    name: examples-opentelemetry-default
  monitoring:
    external: false
  grafana:
    external: false
