name: otel-emitters-dart

networks:
  default:
    external: true
    name: examples-opentelemetry-default

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: otel-emitters-dart-web
    ports:
      - 8051:80


